name: bci-nginx

services:
  nginx:
    build:
      context: .
      dockerfile: Containerfile
    image: bci-nginx:latest
    container_name: bci-nginx
    ports:
      - "80:80"
    networks:
      - bci-net

networks:
  bci-net:
    external: true

